# Generated by Django 5.0.1 on 2024-01-12 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_alter_project_image'),
        ('users', '0003_alter_user_github_alter_user_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='projects',
            field=models.ManyToManyField(blank=True, related_name='users', to='projects.project'),
        ),
    ]
