# Generated by Django 5.0.1 on 2024-01-12 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_projects'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='projects',
        ),
    ]
