# Generated by Django 5.0.1 on 2024-01-11 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_alter_project_owner'),
        ('skills', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='skills',
            field=models.ManyToManyField(related_name='project', to='skills.skill'),
        ),
    ]
